### PR TITLE
variable height

### PR DESCRIPTION
**Pull request by roberthaywesley**
Just changed it so it could accommodate ascii art of any height.

### CODE REVIEW

**Comment by aloisdg** [comment]
Thank you!

**Comment by aloisdg** [comment]
@roberoonska by the way, I opened some [issues](https://github.com/aloisdg/ascolorii/issues). If you want to keep contributing, go ahead ;)

By the way, If you are motivated by the project, I would like to add you as a collaborator.

**Comment by aloisdg** [comment]
@roberoonska What is the use of `let "numberoflines -= 1"` ?

**Comment by roberthaywesley** [comment]
Otherwise the sequence would be 1 number too long. The sequence 0..7 has
eight numbers in it.

**Pull request merged**
